# This workflow has been deprecated in favour of clickdealer/github-actions
# This needs to be left intact to keep existing repositories scanning

name: sonar-scanner

on:
  workflow_call:
    secrets:
      token:
        required: true
      url:
        required: true

jobs:
  sonar-scanner:
    uses: clickdealer/github-actions/.github/workflows/sonar-scanner.yaml@v1
    secrets: inherit
