name: tlz-checks

on:
  workflow_call:
    secrets:
      tfe_token:
        required: true

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: checkov
        uses: bridgecrewio/checkov-action@v12.641.0
        with:
          framework: terraform

  terrascan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: terrascan
        uses: accurics/terrascan-action@v1.4.1
        with:
          iac_type: terraform
          iac_version: v14

  tfdocs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: terraform docs
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          fail-on-diff: true
          output-file: readme.md

  tffmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1

  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: tflint
        uses: reviewdog/action-tflint@v1.13.0
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: tfsec
        uses: reviewdog/action-tfsec@v1.12.1
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true

  tfvalidate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

        # https://github.com/hashicorp/terraform/issues/28490
      - name: hack modules
        continue-on-error: true
        run: mv .github/tlz-checks/*.tf .

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        env:
          TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.tfe_token }}
